package com.excelian.diginexserver.domain;

public enum DocumentType {

    PASSPORT,
    DRIVING_LICENCE,STATE_ID,
    VOTER_ID,
    BIRTH_CERTIFICATE,
    BANK_STATEMENT,
    FACE_IMAGE,
    COMPANY_ACCOUNTS,
    COMPANY_CHANGE_OF_ADDRESS, ANNUAL_RETURN, CONFIRMATION_STATEMENT, STATEMENT_OF_CAPITAL, CHANGE_OF_NAME, INCORPORATION, LIQUIDATION, MISCELLANEOUS, MORTGAGE, CHANGE_OF_OFFICERS,
    RESOLUTION, CREDIT_REPORT, CREDIT_CHECK, REGISTER_REPORT, REGISTER_CHECK, DATA_SUMMARY,
    CHANGE_OF_PSC, ADVERSE_MEDIA, TAX
}
